### PR TITLE
support n-syntax

### PR DESCRIPTION
**Pull request by modosc**
add ssupport for `[^n]` syntax. test case is from the [docs](https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide#footnotes)

### CODE REVIEW

**Comment by tivie** [comment]
thanks @modosc

**Comment by modosc** [comment]
thanks - would you mind doing a npm/bower release?

**Comment by tivie** [comment]
this is for ghost editor. It is supposed to be integrated with that.

**Comment by modosc** [comment]
sure - that's how i'm using it (in a fork). i'd just rather install from npm/bower than install from git.

**Pull request merged**
